version: '3.2'

services:
  db:
    image: postgres:12.1
    container_name: the_coffee_store_db
    environment:
      - POSTGRES_DB=the_coffee_store_development
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.7
    container_name: the_coffee_store_redis
    ports:
      - "6379:6379"
