name: Deploy to Heroku

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: ${{ secrets.HEROKU_APP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.4
        with:
          # 0 indicates fetching history for all branches and tags. This is required to push to Heroku.
          fetch-depth: 0

      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/develop' && job.status == 'success'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
          # https://devcenter.heroku.com/articles/git#deploying-from-a-branch-besides-master
          git push -f production origin/develop:refs/heads/main
