name: Deploy to Heroku

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: ${{ secrets.HEROKU_APP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/develop' && job.status == 'success'
        run: |
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/develop:master
