name: Deploy to Heroku

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: ${{ secrets.HEROKU_APP }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/develop'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
          git push -f production origin/develop:refs/heads/master
